In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
base = '/Users/vincentribberink/Documents/School/Winter 2026/GEOM 4009/Final Project'

agg_path = base + '/agg.csv'
comp_path = base + '/comparison.csv'
geom_path = base + '/peat_shp/peat_polygon_sample.shp'

agg = pd.read_csv(agg_path)
comp = pd.read_csv(comp_path)
geom_gdf = gpd.read_file(geom_path)

In [3]:
geom = geom_gdf.geometry
geom

0    POLYGON Z ((-81.14374 46.62418 0, -81.14354 46...
1    POLYGON Z ((-81.15776 46.62068 0, -81.1582 46....
2    POLYGON Z ((-81.15237 46.62068 0, -81.15263 46...
3    POLYGON Z ((-81.17177 46.61502 0, -81.1727 46....
Name: geometry, dtype: geometry

In [6]:
ice_agg_gdf = gpd.GeoDataFrame(agg[:2].reset_index(drop=True), geometry=geom[-2:].reset_index(drop=True))
gedi_agg_gdf = gpd.GeoDataFrame(agg[2:], geometry=geom)
comp_gdf = gpd.GeoDataFrame(comp, geometry=geom)

ice_agg_gdf = ice_agg_gdf[['polygon_id', 'h_canopy_mean', 'h_canopy_min', 'h_canopy_max', 'h_canopy_std', 'satellite', 'geometry']]
gedi_agg_gdf.drop(columns=['h_canopy_mean', 'h_canopy_min', 'h_canopy_max', 'h_canopy_std'], inplace=True)

In [7]:
ice_agg_gdf

,polygon_id,h_canopy_mean,h_canopy_min,h_canopy_max,h_canopy_std,satellite,geometry
0,3,3.400000e+38,3.400000e+38,3.400000e+38,0.000000e+00,ICESat-2,"POLYGON Z ((-81.15237 46.62068 0, -81.15263 46..."
1,4,1.360000e+38,4.332809e+00,3.400000e+38,1.730000e+38,ICESat-2,"POLYGON Z ((-81.17177 46.61502 0, -81.1727 46...."

In [8]:
comp_gdf = comp_gdf.reset_index()
comp_gdf['polygon_id'] = comp_gdf['index'] + 1
comp_gdf.drop(columns=['index'])

,diff_mean,diff_max,diff_min,diff_std,geometry,polygon_id
0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,"POLYGON Z ((-81.14374 46.62418 0, -81.14354 46...",1
1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,"POLYGON Z ((-81.15776 46.62068 0, -81.1582 46....",2
2,3.402823e+38,3.402823e+38,3.402823e+38,1.470119e-01,"POLYGON Z ((-81.15237 46.62068 0, -81.15263 46...",3
3,1.361129e+38,3.402823e+38,1.517809e+00,1.725546e+38,"POLYGON Z ((-81.17177 46.61502 0, -81.1727 46....",4

In [9]:
ice_agg_gdf

,polygon_id,h_canopy_mean,h_canopy_min,h_canopy_max,h_canopy_std,satellite,geometry
0,3,3.400000e+38,3.400000e+38,3.400000e+38,0.000000e+00,ICESat-2,"POLYGON Z ((-81.15237 46.62068 0, -81.15263 46..."
1,4,1.360000e+38,4.332809e+00,3.400000e+38,1.730000e+38,ICESat-2,"POLYGON Z ((-81.17177 46.61502 0, -81.1727 46...."

In [10]:
out_dir = base + '/step_6'

ice_agg_gdf.rename(columns={'h_canopy_mean':'h_can_mean', 'h_canopy_min':'h_can_min', 'h_canopy_max':'h_can_max', 'h_canopy_std':'h_can_std'}, inplace=True)
gedi_agg_gdf.rename(columns={'elevation_mean':'elev_mean', 'elevation_min':'elev_min', 'elevation_max':'elev_max', 'elevation_std':'elev_std',
                             'canopy_h_mean':'can_h_mean', 'canopy_h_min':'can_h_min', 'canopy_h_max':'can_h_max', 'canopy_h_std':'can_h_std',}, inplace=True)

ice_agg_gdf.to_file((out_dir + '/icesat_agg.shp'))
gedi_agg_gdf.to_file((out_dir + '/gedi_agg.shp'))
comp_gdf.to_file((out_dir + '/comparison.shp'))

ice_agg_gdf.drop(columns=['geometry'], inplace=True)
gedi_agg_gdf.drop(columns=['geometry'], inplace=True)
comp_gdf.drop(columns=['geometry'], inplace=True)

ice_agg_gdf.to_csv((out_dir + '/icesat_agg.csv'))
gedi_agg_gdf.to_csv((out_dir + '/gedi_agg.csv'))
comp_gdf.to_csv((out_dir + '/comparison.csv'))

/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4e+38 of field h_can_mean of feature 0 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4e+38 of field h_can_min of feature 0 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4e+38 of field h_can_max of feature 0 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 1.36e+38 of field h_can_mean of feature 1 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4e+38 of field h_can_max of feature 1 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 1.7299999999999999e+38 of field h_can_std of feature 1 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4028234999999999e+38 of field diff_mean of feature 2 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4028234999999999e+38 of field diff_max of feature 2 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4028234999999999e+38 of field diff_min of feature 2 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 1.3611294e+38 of field diff_mean of feature 3 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 3.4028234999999999e+38 of field diff_max of feature 3 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/usr/local/Caskroom/miniforge/base/envs/geom/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value 1.7255464554691092e+38 of field diff_std of feature 3 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(